#!/bin/sh

# This file used as a git hook by vcsh
#
# the code below moves any tracked-by-vcsh files that are pre-existing on a fresh box
# into seperate dir so that a git clone can proceed without erroring
# files moved can then be inspected by the user and deleted or whatever

#
# the Makefile will place this file in the appropiate vcsh dir 
# where vcsh will run it prior to a git clone 
#
# (doing a git stash may be a more elegant way of doing this if I can be bothered)

set -e
BACKUP_DIR="$HOME/clobbered-by-vcsh/${VCSH_REPO_NAME}-$(date "+%F-%R")"

# move files out of the way
for object in $(git ls-tree --name-only origin/bash); do
  if test -e $object; then
    # create the clobber directory
    [ ! -d "$BACKUP_DIR" ] && mkdir -p "$BACKUP_DIR"
    echo "mv $HOME/$object to $BACKUP_DIR/$object"
    mv "$HOME/$object" "$BACKUP_DIR/$object"
  fi
done

unset BACKUP_DIR
